# Artificial Intelligence
## M Ali
### Lab 10 - Data Pre-Processing

### Step 1: Importing Libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2: Reading the CSV File

In [2]:
data = pd.read_csv('titanic.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

### Step 3: Checking Shape (Rows and Columns)

In [3]:
print('We have {} rows.'.format(data.shape[0]))
print('We have {} columns'.format(data.shape[1]))

We have 418 rows.
We have 12 columns

### Step 4: Checking Null Values

In [4]:
np.sum(pd.isnull(data))

np.int64(414)

### Step 5: Checking Unique Values of a Specific Column

In [5]:
# 1. Pehle column banayein (Ye line sab se upar ho)
data['education'] = 'Higher Secondary'

# 2. Phir uski unique values check karein
print(data['education'].unique())

# 3. Poora table check karein
data.head()

<ArrowStringArray>
['Higher Secondary']
Length: 1, dtype: str

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,education
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Higher Secondary
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Higher Secondary
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Higher Secondary
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Higher Secondary
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Higher Secondary

### Step 6: Filling Null Values with Mode

In [6]:
num = data['education'].mode()[0]
data['education'] = data['education'].fillna(num)

# verify null values are filled
print(np.sum(pd.isnull(data)))

414

### Step 7: Type Conversion to Int

In [7]:
# Pehle text ki jagah number daalein (e.g., 12, 14, 16)
data['education'] = 12 

# Ab isay integer mein convert karein (Ab error nahi aaye ga)
data['education'] = data['education'].astype(int)

data.dtypes
data['education'] = data['education'].astype(np.int64)
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
education        int64
dtype: object

### Step 8: Dropping Unnecessary Columns

In [8]:
# Agar 'id' nahi bhi hoga toh error nahi aaye ga
data.drop('id', axis=1, inplace=True, errors='ignore')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,education
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,12
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,12
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,12
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,12
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,12

### Step 9: Checking Datatypes of All Columns

In [9]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
education        int64
dtype: object

### Step 10: Splitting Data into X and Y

In [10]:
x = data.iloc[:, 0:-1]
print('Shape of x:', x.shape)

y = data.iloc[:, -1]
print('Shape of y:', y.shape)

Shape of x: (418, 12)
Shape of y: (418,)

### Step 11: Converting Object Columns to Int using Factorize

In [11]:
cat_columns = x.select_dtypes(['object']).columns
x[cat_columns] = x[cat_columns].apply(lambda x: pd.factorize(x)[0])
x.dtypes

C:\Users\Person\AppData\Local\Temp\ipykernel_6960\3482138938.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_columns = x.select_dtypes(['object']).columns

PassengerId      int64
Survived         int64
Pclass           int64
Name             int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Ticket           int64
Fare           float64
Cabin            int64
Embarked         int64
dtype: object

### Final Check: View Processed Data

In [12]:
x.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,0,0,34.5,0,0,0,7.8292,-1,0
1,893,1,3,1,1,47.0,1,0,1,7.0000,-1,1
2,894,0,2,2,0,62.0,0,0,2,9.6875,-1,0
3,895,0,3,3,0,27.0,0,0,3,8.6625,-1,1
4,896,1,3,4,1,22.0,1,1,4,12.2875,-1,1